### ISSUE TITLE
Left-Overs

### ISSUE THREAD

**Issue by ekmett** [ekmett/machines#5]
No intrinsic notion of left-overs is handled by the API.

This could be considered both a strength and a curse.

**Comment by YoEight** [comment]
Old comment, but I don't see `Unread` anymore so I guess this issue is still valid. Personally, I never needed this feature but I'd like to see what people expect in this regard

**Comment by ekmett** [comment]
The long term plan has always been to go through and build a "composable language of input transformers". `Unread` is sort of an initial salvo in that act, rather than a final solution.

**Comment by YoEight** [comment]
Do you have an example of such `composable language of input transformers` ? Sounds like something fun to learn

**Comment by ekmett** [comment]
If I knew quite how to encode it, I already would have. =)

But the general idea would be that it'd be nice to be able to have things like T take two other 'input languages' as parameters.

Something like: `T (Is a) (Is b) c` instead of `T a b c`

This would let us do write-back on one input with `T (Stack a) (Is b)` or whatever.

The trick is then figuring out how to write the driver to support this sort of thing.

**Comment by ekmett** [comment]
This particular issue here can be closed. `Unread` became `Stack` in a patch by @glguy a while back.
