### ISSUE TITLE
Composing tees

### ISSUE THREAD

**Issue by treeowl** [ekmett/machines#54]
There doesn't seem to be a nice built-in way to compose tees at present, unless I'm missing something. One possibility might be to do something really simple, like

```Haskell
data GenT j k c =
  Gentle (j c) | Goner (k c)
```

Then `GenT (Is a) (T een ager)` should be a three-way `T`, I believe.

**Comment by ekmett** [comment]
The main issue is that none of the combinators work with such a beast. This is why I've been kicking around an alternate set of multicategory-based foundations.
