### ISSUE TITLE
Some types are too general

### ISSUE THREAD

**Issue by treeowl** [ekmett/machines#57]
I ran into a nasty bug today where I `repeatedly` invoked an action lifted to a `PlanT` but forgot to `yield` it.  This surely would not have happened if `repeatedly` had insisted that my plan return `()`. The same applies to `construct`, and likely some other functions. I don't know how large the performance impact would be of requiring `() <$` for any plan of the wrong type, but it's a price I'd personally be willing to pay most of the time.

**Comment by treeowl** [comment]
Note: the current versions completely defeat HLint warnings about unused monadic results.

```haskell
repeatedly $ do
  money <- withdrawFromBank
  buyTelevision money
```

gets me no warnings, whereas

```haskell
repeatedly $ do
  money <- withdrawFromBank
  buyTelevision money
  return ()
```

would warn me that I'd left my televisions on the curb.

**Comment by treeowl** [comment]
I took a look at the Core (with `-O2`). It's completely identical, so there shouldn't be any performance impact whatsoever.

**Comment by ekmett** [comment]
I'm actually a rather big opponent of that warning.

Forcing users to use `() <$` can have non-trivial operational issues whenever the monad `isn't` concrete.

**Comment by ekmett** [comment]
I'm going to close this out as an 'agree to disagree'.

**Comment by treeowl** [comment]
Inlining is sufficient in this case; specialization isn't necessary (the Core I was looking at was polymorphic in the `Monad`). I wasted something like two hours tracking down an infinite loop caused by this problem. 2 hours is more than 0.

**Comment by ekmett** [comment]
Let's see what happens:

```haskell
    PlanT m >>= const (return ())
      = PlanT (\kp ke kr kf -> m (\a -> runPlanT (const (return ()) a) kp ke kr kf) ke kr kf) 
      = PlanT (\kp ke kr kf -> m (\a -> runPlanT (return ()) kp ke kr kf) ke kr kf)
      = PlanT (\kp ke kr kf -> m (\a -> (\kp _ _ _ -> kp ()) kp ke kr kf) ke kr kf)
      = PlanT (\kp ke kr kf -> m (\a -> kp ()) ke kr kf)
```

is different than `PlanT m`, it pays for the extra set up of the ().

But when we apply it in repeatedly:

```haskell
    repeatedly m = r where
      r = MachineT $ runPlanT m
        (const (runMachineT r))
        (\o k -> return (Yield o (MachineT k)))
        (\f k g -> return (Await (MachineT . f) k (MachineT g)))
        (return Stop)
      = MachineT $ runPlanT (m >>= const (return ())
          (const (runMachineT r))
          (\o k -> return (Yield o (MachineT k)))
          (\f k g -> return (Await (MachineT . f) k (MachineT g)))
          (return Stop)
       = MachineT $ (\kp ke kr kf -> m (\a -> kp ()) ke kr kf)
          (const (runMachineT r))
          (\o k -> return (Yield o (MachineT k)))
          (\f k g -> return (Await (MachineT . f) k (MachineT g)))
          (return Stop)
       = MachineT $ m (\a -> const (runMachineT r) ()) 
          (\o k -> return (Yield o (MachineT k)))
          (\f k g -> return (Await (MachineT . f) k (MachineT g)))
          (return Stop)
         = MachineT $ m (\a -> runMachineT r) 
          (\o k -> return (Yield o (MachineT k)))
          (\f k g -> return (Await (MachineT . f) k (MachineT g)))
          (return Stop)
```

Which does indeed look like what I get the other way around, independent of the underlying monad `m`, thanks to the CPSing I do in `PlanT`, so yes, you get the core you're mentioning.

**Comment by ekmett** [comment]
That said, this won't always happen. 

If you don't have a fully known plan, then the above still will fail to optimize. It only optimizes when we know we have `repeatedly (m >>= return ())` and the two halves meet up concretely in the optimizer -- not when we have `repeatedly m` and the last action in it happens to be `return ()`

**Comment by treeowl** [comment]
I think that can only be a problem if we don't know that we have
`repeatedly`, which seems rather unlikely to me. Otherwise, if the plan
returns () nothing changes, and otherwise we void it quite visibly unless
we're slowing things down on purpose.

**Comment by ekmett** [comment]
In general I'm not going to accept pull requests in this direction to edit the existing combinators to make them have more restrictive type signatures in this way. I feel rather more strongly about this particular issue than is easily conveyed. Hence why 

> I'm going to close this out as an 'agree to disagree'.

In general, I have a policy that holds across every one of my package of returning an `a` in positive position when it would be uninhabited/Void to avoid needless conversions with `fmap absurd` and accepting `a` when I don't use the argument to avoid needless conversions with `void`.

`repeatedly` is no more dangerous than `traverse_` in this regard, and I'll fight and die to avoid having _that_ change. ;)

**Comment by treeowl** [comment]
There's a reason this wasn't a pull request. I knew there wasn't much
chance of changing the current functions, and I couldn't think of good
names for the ones I want.
