### ISSUE TITLE
machines-0.6 requires distributive < 0.5

### ISSUE THREAD

**Issue by DanBurton** [ekmett/machines#75]
Can you release a version of machines that works with distributive-0.5.*?

**Comment by DanBurton** [comment]
This is the only thing that is constraining machines on stackage right now.
https://github.com/fpco/stackage/issues/1128

**Comment by ekmett** [comment]
I think so. @RyanGlScott can you think of any issues?

**Comment by RyanGlScott** [comment]
Nope, `distributive-0.5` works fine with `machines`. I've merged #74 and #76, which bring all the dependencies up to date.

**Comment by glguy** [comment]
fixed in 0.6.1 and released to hackage
